server.port: 8080
spring.profiles: default
api.impactnalysis.settings:
  tokenExpirationTime: 15 #minutes
  refreshTokenExpTime: 60 #minutes
  tokenIssuer: azharrnaeem@gmail.com
  secretKeySignatureAlgo: HS256
  covidDataSourceURL: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
  dataRefreshInterval: PT10H #10 hours configured as data refresh interval
  
spring.datasource:
  url: "jdbc:h2:mem:testdb"
  driverClassName: org.h2.Driver
  username: sa
  password: ""
  data: "classpath*:data.sql"
spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect

spring.h2.console.enabled: true
spring.jackson.default-property-inclusion: non_null